services:
  - type: web
    plan: free
    name: asset-manager-web
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn asset_manager.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: ALLOWED_HOSTS
        value: 'asset-manager.onrender.com'
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4