# Generated by Django 5.1.4 on 2025-01-02 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_asset_description_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
