# Generated by Django 5.1.4 on 2025-01-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_assignmenthistory_maintenancehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='status_after',
        ),
    ]
