# Generated by Django 5.1.4 on 2025-01-02 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_asset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=450, null=True, validators=[django.core.validators.MaxLengthValidator(450, message='Description cannot be longer than 450 characters.')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(1, message='Asset name cannot be empty.'), django.core.validators.MaxLengthValidator(200, message='Asset name cannot be longer than 200 characters.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=75, null=True, validators=[django.core.validators.MinLengthValidator(1, message='Name cannot be empty.'), django.core.validators.MaxLengthValidator(75, message='Name cannot be longer than 200 characters.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with an optional '+' followed by digits, with optional spaces, parentheses, hyphens, or plus signs.", regex='^\\+?(\\(\\d{1,4}\\)|\\d{1,4})?[\\s\\-]?\\d{1,4}[\\s\\-]?\\d{1,4}[\\s\\-]?\\d{1,4}$')]),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500, message='Description cannot be longer than 500 characters.')]),
        ),
    ]
