# Generated by Django 5.1.4 on 2025-01-02 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_asset_description_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=450, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters long.')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Asset name must contain at least one word and may include letters, numbers, and spaces only.', regex='^(?=.*[a-zA-Z])[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Name must contain at least one word and only letters and spaces are allowed.', regex='^(?=.*[a-zA-Z])[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with an optional '+' followed by an optional area code in parentheses or digits, and include groups of digits separated by optional spaces or hyphens.", regex='^\\+?(\\(\\d{1,4}\\)|\\d{1,4})?[\\s\\-]?\\d{1,4}[\\s\\-]?\\d{1,4}[\\s\\-]?\\d{1,4}$')]),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters long.')]),
        ),
    ]
