# Generated by Django 5.1.4 on 2025-01-02 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_asset_description_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=450, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters, or left empty.')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Asset name must contain at least one letter and cannot consist solely of special characters or numbers.', regex='^(?=.*[a-zA-Z])(?=.*[a-zA-Z0-9]).+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Name must contain at least one letter and cannot consist solely of special characters or numbers.', regex='^(?=.*[a-zA-Z])(?=.*[a-zA-Z0-9]).+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with an optional '+' followed by digits, with optional spaces, parentheses, or hyphens.", regex='^\\+?(\\(\\d{1,4}\\)|\\d{1,4})?[\\s\\-]?\\d{1,4}[\\s\\-]?\\d{1,4}[\\s\\-]?\\d{1,4}$')]),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters or left empty.')]),
        ),
    ]
